[package]
name = "kuebel"
version = "0.1.0"
description = "Ein kleiner S3-Browser fuer macOS, Windows und Linux"
authors = ["Complioty GmbH"]
edition = "2021"

[lib]
name = "kuebel_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
aws-credential-types = "1"
uuid = { version = "1", features = ["v4"] }
percent-encoding = "2"




[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
